// exportPdf.js — Professional PDF report generator for AI Analysis charts.
// Uses jsPDF for layout and html2canvas to capture Recharts SVG charts.
import { jsPDF } from 'jspdf'
import html2canvas from 'html2canvas'
import { formatCurrency, formatPercentage, MONTHS_FULL } from './analytics'
import { robotoRegularBase64, robotoBoldBase64 } from './robotoFont'
import barangayLogoUrl from '../assets/brgy-logo-2.png'
import skLogoUrl from '../assets/logo.png'

// ── Constants ──────────────────────────────────────────────────────────────────
const PAGE_W = 210    // A4 width mm
const PAGE_H = 297    // A4 height mm
const MARGIN = 16     // print-safe but compact — leaves room to spare without wasting a page
const CONTENT_W = PAGE_W - MARGIN * 2
const FOOTER_Y = PAGE_H - 12
// How much space content must leave at the bottom of every page for the
// footer (rule + one or two text lines) to have clear room, never overlap.
const BOTTOM_RESERVE = 24

// One vertical rhythm for the whole report instead of a different hand-picked
// gap after every block. Every section, table, and strip closes on one of
// these, which is what keeps the spacing looking deliberate rather than
// accidental.
const SPACE = {
  xs: 2,    // a nudge between two blocks that belong to each other
  sm: 4,    // heading to the thing it labels
  md: 7,    // between blocks inside one section
  lg: 11,   // between sections
}

const COLORS = {
  brand:    [14, 107, 77],   // #0E6B4D
  dark:     [15, 31, 54],    // #0F1F36
  text:     [55, 65, 81],    // #374151
  muted:    [107, 114, 128], // #6B7280
  line:     [229, 231, 235], // #E5E7EB
  white:    [255, 255, 255],
  bgLight:  [249, 250, 251], // #F9FAFB
  danger:   [220, 107, 79],  // #DC6B4F
}

// ── Helpers ────────────────────────────────────────────────────────────────────

function initPdfDoc(orientation = 'portrait') {
  const doc = new jsPDF(orientation, 'mm', 'a4')
  doc.addFileToVFS('Roboto-Regular.ttf', robotoRegularBase64)
  doc.addFont('Roboto-Regular.ttf', 'Roboto', 'normal')
  doc.addFileToVFS('Roboto-Bold.ttf', robotoBoldBase64)
  doc.addFont('Roboto-Bold.ttf', 'Roboto', 'bold')
  doc.setFont('Roboto', 'normal')
  return doc
}

function setColor(doc, color) {
  doc.setTextColor(...color)
}

function drawLine(doc, y) {
  doc.setDrawColor(...COLORS.line)
  doc.setLineWidth(0.3)
  doc.line(MARGIN, y, PAGE_W - MARGIN, y)
}

function addFooter(doc, pageNum, totalPages, { confidentialityNote } = {}) {
  // The confidentiality note gets its own line above the main one — sharing
  // a baseline with the left-aligned system name was overlapping it, since
  // both are long enough to reach past the page's horizontal center.
  const ruleY = confidentialityNote ? FOOTER_Y - 9 : FOOTER_Y - 5

  // The footer is stamped onto finished pages, so it inherits whatever font
  // weight the body content last left set — it has to state its own.
  doc.setFont('Roboto', 'normal')

  doc.setDrawColor(...COLORS.line)
  doc.setLineWidth(0.3)
  doc.line(MARGIN, ruleY, PAGE_W - MARGIN, ruleY)

  if (confidentialityNote) {
    doc.setFontSize(6.5)
    setColor(doc, COLORS.muted)
    doc.text(confidentialityNote, PAGE_W / 2, FOOTER_Y - 4, { align: 'center' })
  }

  doc.setFontSize(8)
  setColor(doc, COLORS.muted)
  doc.text(`Page ${pageNum} of ${totalPages}`, PAGE_W - MARGIN, FOOTER_Y, { align: 'right' })
  doc.text('Generated by Cuenta — SK Budget Monitoring System', MARGIN, FOOTER_Y)
}

// A tight but safe bottom reserve — just enough for the footer and its rule,
// so a section keeps filling the page right up until it genuinely runs out
// of room instead of jumping to a fresh page early and leaving a gap behind.
//
// Exposes whether it actually broke, not just the resulting y — callers that
// need to redo per-page setup (a table redrawing its header row on the new
// page, say) can't tell a break happened from the y alone, since a page that
// was nearly full could coincidentally reset to close to the same value.
function pageBreakInfo(doc, y, needed = 30) {
  if (y + needed > PAGE_H - BOTTOM_RESERVE) {
    doc.addPage()
    return { y: MARGIN + 8, broke: true }
  }
  return { y, broke: false }
}

function checkPageBreak(doc, y, needed = 30) {
  return pageBreakInfo(doc, y, needed).y
}

// ── Chart capture ──────────────────────────────────────────────────────────────

async function captureChartImage(chartContainerEl) {
  if (!chartContainerEl) return null
  // Allocation exports opt into capturing their detailed HTML legend as well
  // as the Recharts SVG. Other reports keep capturing only the chart wrapper.
  const captureFull = chartContainerEl.dataset?.pdfCapture === 'full'
  const captureTarget = captureFull
    ? chartContainerEl
    : chartContainerEl.querySelector('.recharts-responsive-container') || chartContainerEl
  const requestedScale = Number(chartContainerEl.dataset?.pdfScale)
  const scale = Number.isFinite(requestedScale) && requestedScale >= 2 ? requestedScale : 2
  try {
    const canvas = await html2canvas(captureTarget, {
      backgroundColor: '#ffffff',
      scale,
      useCORS: true,
      logging: false,
    })
    return { dataUrl: canvas.toDataURL('image/png'), width: canvas.width, height: canvas.height }
  } catch (err) {
    console.warn('Chart capture failed:', err)
    return null
  }
}

// Fits a captured image inside a maxWidth x maxHeight box without distorting
// its aspect ratio (avoids squishing/cropping variable-height content like a
// pie chart + legend list).
function fitImageBox(image, maxWidth, maxHeight) {
  const naturalRatio = image.width / image.height
  let w = maxWidth
  let h = w / naturalRatio
  if (h > maxHeight) {
    h = maxHeight
    w = h * naturalRatio
  }
  return { w, h }
}

// ── Report Header ──────────────────────────────────────────────────────────────

function drawReportHeader(doc, { title, year, month, view = 'yearly', generatedAt, meta }) {
  let y = MARGIN

  // Brand bar
  doc.setFillColor(...COLORS.brand)
  doc.rect(0, 0, PAGE_W, 4, 'F')

  // System name
  y += 8
  doc.setFontSize(10)
  setColor(doc, COLORS.brand)
  doc.setFont('Roboto', 'bold')
  doc.text('CUENTA', MARGIN, y)
  doc.setFont('Roboto', 'normal')
  setColor(doc, COLORS.muted)
  doc.setFontSize(8)
  doc.text('SK Budget Monitoring and Documentation Tracking with AI Analysis', MARGIN, y + 5)

  // Report title
  y += 16
  doc.setFontSize(18)
  doc.setFont('Roboto', 'bold')
  setColor(doc, COLORS.dark)
  doc.text(title, MARGIN, y)

  // Meta line
  y += 8
  doc.setFontSize(9)
  doc.setFont('Roboto', 'normal')
  setColor(doc, COLORS.muted)
  const selectedMonth = view === 'monthly' && month ? MONTHS_FULL[Number(month) - 1] : 'All months'
  const metaLine = meta || `Month: ${selectedMonth}  •  Year: ${year}  •  Generated: ${generatedAt}`
  doc.text(metaLine, MARGIN, y)

  y += 4
  drawLine(doc, y)

  return y + 8
}

// ── Official Letterhead Header ───────────────────────────────────────────────
// The government-style letterhead used by Cuenta's generated documents
// (Transmittal Letter, Purchase Request, etc.): the barangay seal and the SK
// logo flanking a centered Republic-of-the-Philippines text block. Reused
// here for the Expenses page's Export PDF report, at the barangay's request.

const imageDataUrlCache = new Map()

// jsPDF's addImage needs a base64 data URL (or an <img>/<canvas>), not the
// plain asset URL Vite gives an imported PNG — fetch it once per session and
// convert it, so a second export in the same tab skips the round trip.
async function loadImageAsDataUrl(url) {
  if (imageDataUrlCache.has(url)) return imageDataUrlCache.get(url)

  const promise = (async () => {
    const response = await fetch(url)
    const blob = await response.blob()
    return await new Promise((resolve, reject) => {
      const reader = new FileReader()
      reader.onload = () => resolve(reader.result)
      reader.onerror = () => reject(new Error('Could not read a letterhead logo image.'))
      reader.readAsDataURL(blob)
    })
  })()

  imageDataUrlCache.set(url, promise)
  return promise
}

async function drawOfficialLetterheadHeader(doc, { title, subtitle, meta }) {
  const centerX = PAGE_W / 2
  const logoSize = 18
  let y = MARGIN

  try {
    const [barangayLogo, skLogo] = await Promise.all([
      loadImageAsDataUrl(barangayLogoUrl),
      loadImageAsDataUrl(skLogoUrl),
    ])
    doc.addImage(barangayLogo, 'PNG', MARGIN, y, logoSize, logoSize)
    doc.addImage(skLogo, 'PNG', PAGE_W - MARGIN - logoSize, y, logoSize, logoSize)
  } catch (err) {
    // The report is still useful without the seals — never let a failed
    // image fetch block the export itself.
    console.warn('Could not embed the letterhead logos:', err)
  }

  let textY = y + 4
  setColor(doc, COLORS.dark)
  doc.setFontSize(8.5)
  doc.setFont('Roboto', 'normal')
  doc.text('Republic of the Philippines', centerX, textY, { align: 'center' })

  textY += 4.2
  doc.setFont('Roboto', 'bold')
  doc.text('REGION XII', centerX, textY, { align: 'center' })

  textY += 4.2
  doc.setFont('Roboto', 'normal')
  doc.text('Province of Cotabato', centerX, textY, { align: 'center' })

  textY += 4.2
  doc.text('Municipality of Midsayap', centerX, textY, { align: 'center' })

  textY += 4.2
  doc.setFont('Roboto', 'bold')
  doc.text('BARANGAY UPPER GLAD II', centerX, textY, { align: 'center' })

  // A step up in size marks this as the office issuing the report, not just
  // another line in the address, without needing a big gap to do it.
  textY += 6
  doc.setFontSize(10.5)
  doc.text('OFFICE OF THE SANGGUNIANG KABATAAN', centerX, textY, { align: 'center' })

  y = Math.max(textY, y + logoSize) + 8

  doc.setFontSize(13.5)
  doc.setFont('Roboto', 'bold')
  setColor(doc, COLORS.dark)
  doc.text(title, centerX, y, { align: 'center' })
  y += 4

  // Names the period the report covers (e.g. the month) right under the
  // title, so it is the first thing read rather than a field further down.
  if (subtitle) {
    y += 2.5
    doc.setFontSize(11)
    doc.setFont('Roboto', 'bold')
    setColor(doc, COLORS.dark)
    doc.text(subtitle, centerX, y, { align: 'center' })
  }

  if (meta) {
    y += 4
    doc.setFontSize(8.5)
    doc.setFont('Roboto', 'normal')
    setColor(doc, COLORS.muted)
    doc.text(meta, centerX, y, { align: 'center' })
  }

  y += 5
  drawLine(doc, y)

  return y + 6
}

// ── Data Table ─────────────────────────────────────────────────────────────────

// `ruled` swaps the colored-header-bar/zebra-striped look for a clean
// horizontally-ruled table — a rule above and below the column headers,
// hairlines between rows, a closing rule at the bottom, and no vertical
// lines at all. The vertical lines are what made the expenses report read
// as a raw spreadsheet dump; without them the eye tracks each row straight
// across to its amount. Off by default so the other PDF exports built on
// this same table keep their existing look; the Expenses report opts in.
//
// `totalRow` ({ label, value, color }) renders one emphasised summary row
// inside the table's own frame — rule above, bold text, same column edges —
// instead of leaving a detached grey box floating underneath it.
function drawDataTable(doc, { columns, rows, startY, headerColor = COLORS.brand, ruled = false, totalRow = null }) {
  let y = startY
  const colWidths = columns.map((c) => c.width || Math.floor(CONTENT_W / columns.length))

  // Adjust last column to fill remaining width
  const usedWidth = colWidths.slice(0, -1).reduce((a, b) => a + b, 0)
  colWidths[colWidths.length - 1] = CONTENT_W - usedWidth

  // Ruled rows sit tighter than the boxed ones did: the old 8mm floor with
  // 2.6mm padding left every table looking stretched and half-empty, which
  // is most of what made a page of them feel messy.
  const cellPadX = ruled ? 3 : 4
  const cellPadY = ruled ? 2 : 2.6
  const lineHeight = ruled ? 3.9 : 4.1
  const minRowHeight = ruled ? 6.8 : 8
  const headerHeight = ruled ? 7.4 : 9

  // The three rule weights a ruled table uses, and nothing else: a dark
  // frame rule top and bottom, a mid rule under the headers and above the
  // total, and a hairline between data rows.
  function hRule(atY, weight) {
    const spec = {
      frame: [COLORS.dark, 0.35],
      mid: [COLORS.muted, 0.22],
      hair: [COLORS.line, 0.15],
    }[weight]
    doc.setDrawColor(...spec[0])
    doc.setLineWidth(spec[1])
    doc.line(MARGIN, atY, MARGIN + CONTENT_W, atY)
  }

  // Draws the header row at whatever y it's given and returns the y just
  // below it — called once up front, and again on every page a table's rows
  // spill onto, so a continuation page is still a recognizable table with a
  // header, not bare text.
  function renderHeader(atY) {
    const baseline = atY + headerHeight / 2 + 1.3
    let hx = MARGIN

    if (ruled) {
      // Small letter-spaced uppercase labels in muted grey: they read as
      // column captions rather than competing with the figures beneath.
      hRule(atY, 'frame')
      doc.setFontSize(7)
      doc.setFont('Roboto', 'bold')
      setColor(doc, COLORS.muted)
      columns.forEach((col, i) => {
        const right = col.align === 'right'
        const tx = right ? hx + colWidths[i] - cellPadX : hx + cellPadX
        doc.text(String(col.header).toUpperCase(), tx, baseline, right
          ? { align: 'right', charSpace: 0.25 }
          : { charSpace: 0.25 })
        hx += colWidths[i]
      })
      hRule(atY + headerHeight, 'mid')
    } else {
      // Header row — every header is centered over its column, regardless
      // of how that column's own values align, so the banner reads as one
      // clean row rather than following each column's data alignment.
      doc.setFillColor(...headerColor)
      doc.rect(MARGIN, atY, CONTENT_W, headerHeight, 'F')
      doc.setFontSize(8)
      doc.setFont('Roboto', 'bold')
      setColor(doc, COLORS.white)
      columns.forEach((col, i) => {
        doc.text(col.header, hx + colWidths[i] / 2, baseline, { align: 'center' })
        hx += colWidths[i]
      })
    }

    return atY + headerHeight
  }

  y = checkPageBreak(doc, y, headerHeight + 10)
  y = renderHeader(y)

  // Data rows — each cell's text is wrapped to its column width up front,
  // so a row can grow tall enough to fit its longest cell (usually
  // Description) instead of a fixed height that lets long text spill into
  // the row below it.
  //
  // The body face is re-stated on every row rather than once before the
  // loop: a row that spills onto a new page redraws the header, and the
  // header leaves the font bold — which was setting every row on every
  // continuation page in bold.
  rows.forEach((row, rowIndex) => {
    doc.setFont('Roboto', 'normal')
    doc.setFontSize(8)

    const cellLines = columns.map((col, i) => {
      const value = col.format ? col.format(row) : String(row[col.key] ?? '—')
      return doc.splitTextToSize(value, colWidths[i] - cellPadX * 2)
    })
    const maxLines = Math.max(1, ...cellLines.map((lines) => lines.length))
    const rowHeight = Math.max(minRowHeight, cellPadY * 2 + maxLines * lineHeight)

    const broken = pageBreakInfo(doc, y, rowHeight + 8)
    y = broken.y
    if (broken.broke && ruled) y = renderHeader(y)

    // Re-stated after the header, not just before the measuring above, since
    // rendering a continuation header leaves the font bold and small.
    doc.setFont('Roboto', 'normal')
    doc.setFontSize(8)

    if (ruled) {
      // A hairline above every row but the first — the header already has
      // its own rule, and doubling them there reads as a heavy border.
      if (rowIndex > 0 && !broken.broke) hRule(y, 'hair')
    } else if (rowIndex % 2 === 0) {
      doc.setFillColor(...COLORS.bgLight)
      doc.rect(MARGIN, y, CONTENT_W, rowHeight, 'F')
    }

    let x = MARGIN
    columns.forEach((col, i) => {
      const isNegative = col.highlightNegative && typeof row[col.key] === 'number' && row[col.key] < 0
      const customColor = col.colorFor ? col.colorFor(row) : null
      setColor(doc, isNegative ? COLORS.danger : (customColor || COLORS.text))

      const textX = col.align === 'right' ? x + colWidths[i] - cellPadX : x + cellPadX
      const textAlign = col.align === 'right' ? { align: 'right' } : {}
      let lineY = y + cellPadY + lineHeight - 1.3
      cellLines[i].forEach((line) => {
        doc.text(line, textX, lineY, textAlign)
        lineY += lineHeight
      })
      x += colWidths[i]
    })

    y += rowHeight
  })

  if (ruled && totalRow) {
    const rowHeight = minRowHeight + 1
    const broken = pageBreakInfo(doc, y, rowHeight + 8)
    y = broken.y
    if (broken.broke) y = renderHeader(y)

    hRule(y, 'mid')
    const baseline = y + rowHeight / 2 + 1.3
    doc.setFontSize(8)
    doc.setFont('Roboto', 'bold')
    setColor(doc, COLORS.dark)
    doc.text(totalRow.label, MARGIN + cellPadX, baseline)
    setColor(doc, totalRow.color || COLORS.dark)
    doc.text(String(totalRow.value), MARGIN + CONTENT_W - cellPadX, baseline, { align: 'right' })
    y += rowHeight
  }

  if (ruled) hRule(y, 'frame')

  return y + (ruled ? SPACE.md : 6)
}

// ── Summary Box ────────────────────────────────────────────────────────────────

function drawSummaryBox(doc, { title, items, startY }) {
  const rowH = 11
  const topPad = 9
  const bottomPad = 7
  const boxH = topPad + items.length * rowH + bottomPad

  // Section heading — kept with its box on the same page, and given its own
  // clear gap from whatever content came before it.
  let y = checkPageBreak(doc, startY, boxH + 18)
  doc.setFontSize(12)
  doc.setFont('Roboto', 'bold')
  setColor(doc, COLORS.dark)
  doc.text(title, MARGIN, y)
  y += 8

  const boxTop = y
  doc.setFillColor(...COLORS.bgLight)
  doc.setDrawColor(...COLORS.line)
  doc.roundedRect(MARGIN, boxTop, CONTENT_W, boxH, 3, 3, 'FD')

  let rowY = boxTop + topPad
  items.forEach((item) => {
    doc.setFontSize(9)
    doc.setFont('Roboto', 'normal')
    setColor(doc, COLORS.muted)
    doc.text(item.label, MARGIN + 10, rowY)

    doc.setFont('Roboto', 'bold')
    setColor(doc, item.color || COLORS.dark)
    doc.text(item.value, MARGIN + CONTENT_W - 12, rowY, { align: 'right' })
    rowY += rowH
  })

  return boxTop + boxH + 12
}

// ── Graph Structure Box ────────────────────────────────────────────────────────

function drawGraphStructure(doc, { title, items, startY }) {
  let y = checkPageBreak(doc, startY, 10 + items.length * 7)

  doc.setFontSize(10)
  doc.setFont('Roboto', 'bold')
  setColor(doc, COLORS.dark)
  doc.text(title, MARGIN, y)
  y += 6

  items.forEach((item) => {
    y = checkPageBreak(doc, y, 7)
    doc.setFontSize(8)
    doc.setFont('Roboto', 'bold')
    setColor(doc, COLORS.brand)
    doc.text('•', MARGIN + 4, y)
    doc.text(item.label + ':', MARGIN + 9, y)
    doc.setFont('Roboto', 'normal')
    setColor(doc, COLORS.text)
    doc.text(item.value, MARGIN + 9 + doc.getTextWidth(item.label + ':  '), y)
    y += 7
  })

  return y + 4
}

// ═══════════════════════════════════════════════════════════════════════════════
// PUBLIC: Export Budget vs Actual PDF
// ═══════════════════════════════════════════════════════════════════════════════

export async function exportBudgetVsActualPdf({ chartRef, bva, filters }) {
  const doc = initPdfDoc('portrait')
  const now = new Date()
  const generatedAt = now.toLocaleString()

  // ── Page 1: Header ──
  let y = drawReportHeader(doc, {
    title: 'Budget vs Actual Spending',
    year: filters.year,
    month: filters.month,
    view: filters.view,
    generatedAt,
  })

  // ── Chart Image ──
  const chartImg = await captureChartImage(chartRef)
  if (chartImg) {
    y = checkPageBreak(doc, y, 85)
    doc.setFontSize(10)
    doc.setFont('Roboto', 'bold')
    setColor(doc, COLORS.dark)
    doc.text('Approved Budget vs Actual Expenses', MARGIN, y)
    y += 4

    // Subtle border around chart
    doc.setDrawColor(...COLORS.line)
    doc.setLineWidth(0.3)
    doc.roundedRect(MARGIN, y, CONTENT_W, 72, 2, 2, 'S')
    doc.addImage(chartImg.dataUrl, 'PNG', MARGIN + 2, y + 2, CONTENT_W - 4, 68)
    y += 78
  }

  // ── Graph Structure ──
  y = drawGraphStructure(doc, {
    title: 'Graph Structure',
    startY: y,
    items: [
      { label: 'X-Axis', value: 'Months' },
      { label: 'Y-Axis', value: 'Amount (₱)' },
      { label: 'Series 1', value: 'Approved Budget' },
      { label: 'Series 2', value: 'Actual Expenses' },
    ],
  })

  // ── Data Table ──
  y = checkPageBreak(doc, y, 20)
  doc.setFontSize(11)
  doc.setFont('Roboto', 'bold')
  setColor(doc, COLORS.dark)
  doc.text('Budget vs Spending Data', MARGIN, y)
  y += 6

  const tableColumns = [
    { key: 'label', header: 'Month', width: 36 },
    { key: 'budget', header: 'Approved Budget', align: 'right', width: 38, format: (r) => formatCurrency(r.budget, { detailed: true }) },
    { key: 'spending', header: 'Actual Expenses', align: 'right', width: 38, format: (r) => formatCurrency(r.spending, { detailed: true }) },
    { key: 'variance', header: 'Remaining Budget', align: 'right', width: 36, format: (r) => formatCurrency(r.variance, { detailed: true }), highlightNegative: true },
    { key: 'percentUsed', header: 'Utilization', align: 'right', width: 26, format: (r) => formatPercentage(r.percentUsed, 2) },
  ]

  y = drawDataTable(doc, {
    columns: tableColumns,
    rows: bva.rowsWithData,
    startY: y,
  })

  // ── Budget Summary ──
  const totalBudget = bva.totalBudget
  const totalSpending = bva.totalSpending
  const totalVariance = bva.totalVariance
  const overallUtilization = totalBudget > 0 ? (totalSpending / totalBudget) * 100 : 0

  drawSummaryBox(doc, {
    title: 'Budget Summary',
    startY: y,
    items: [
      { label: 'Total Approved Budget', value: formatCurrency(totalBudget, { detailed: true }) },
      { label: 'Total Actual Expenses', value: formatCurrency(totalSpending, { detailed: true }) },
      { label: 'Total Remaining Budget', value: formatCurrency(totalVariance, { detailed: true }), color: totalVariance < 0 ? COLORS.danger : COLORS.brand },
      { label: 'Overall Utilization', value: formatPercentage(overallUtilization, 2) },
    ],
  })

  // ── Page numbers ──
  const totalPages = doc.internal.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    addFooter(doc, i, totalPages)
  }

  const periodSlug = filters.view === 'monthly' ? `${filters.year}-${String(filters.month).padStart(2, '0')}` : filters.year
  doc.save(`budget-vs-actual-${periodSlug}.pdf`)
}

// ═══════════════════════════════════════════════════════════════════════════════
// PUBLIC: Export Monthly Spending Trend PDF
// ═══════════════════════════════════════════════════════════════════════════════

export async function exportMonthlySpendingPdf({ chartRef, tableRows, filters }) {
  const doc = initPdfDoc('portrait')
  const now = new Date()
  const generatedAt = now.toLocaleString()

  // ── Page 1: Header ──
  let y = drawReportHeader(doc, {
    title: 'Monthly Spending Trend',
    year: filters.year,
    month: filters.month,
    view: filters.view,
    generatedAt,
  })

  // ── Chart Image ──
  const chartImg = await captureChartImage(chartRef)
  if (chartImg) {
    y = checkPageBreak(doc, y, 85)
    doc.setFontSize(10)
    doc.setFont('Roboto', 'bold')
    setColor(doc, COLORS.dark)
    doc.text(`Monthly Spending — ${filters.year}`, MARGIN, y)
    y += 4

    doc.setDrawColor(...COLORS.line)
    doc.setLineWidth(0.3)
    doc.roundedRect(MARGIN, y, CONTENT_W, 72, 2, 2, 'S')
    doc.addImage(chartImg.dataUrl, 'PNG', MARGIN + 2, y + 2, CONTENT_W - 4, 68)
    y += 78
  }

  // ── Graph Structure ──
  y = drawGraphStructure(doc, {
    title: 'Graph Structure',
    startY: y,
    items: [
      { label: 'X-Axis', value: 'Months' },
      { label: 'Y-Axis', value: 'Spending Amount (₱)' },
      { label: 'Series', value: 'Actual Monthly Spending' },
    ],
  })

  // ── Data Table ──
  y = checkPageBreak(doc, y, 20)
  doc.setFontSize(11)
  doc.setFont('Roboto', 'bold')
  setColor(doc, COLORS.dark)
  doc.text('Monthly Spending Data', MARGIN, y)
  y += 6

  // Build change from previous month
  const dataWithChange = tableRows.map((r, i) => {
    const prev = i > 0 ? tableRows[i - 1].total : null
    const change = prev != null ? r.total - prev : null
    let trendDir = '—'
    if (change !== null) {
      trendDir = change > 0 ? 'Increasing' : change < 0 ? 'Decreasing' : 'Stable'
    }
    return { ...r, changeAmount: change, trendDirection: trendDir }
  })

  const tableColumns = [
    { key: 'monthFull', header: 'Month', width: 30 },
    { key: 'total', header: 'Total Spending', align: 'right', width: 36, format: (r) => formatCurrency(r.total, { detailed: true }) },
    { key: 'changeAmount', header: 'Change', align: 'right', width: 36, format: (r) => r.changeAmount !== null ? (r.changeAmount > 0 ? '+' : '') + formatCurrency(r.changeAmount, { detailed: true }) : '—', highlightNegative: false },
    { key: 'trendDirection', header: 'Trend', width: 24 },
    { key: 'count', header: 'Approved', align: 'right', width: 20, format: (r) => String(r.count) },
    { key: 'missing', header: 'Missing Receipts', align: 'right', width: 28, format: (r) => String(r.missing) },
  ]

  y = drawDataTable(doc, {
    columns: tableColumns,
    rows: dataWithChange,
    startY: y,
  })

  // ── Spending Summary ──
  const totalSpending = tableRows.reduce((a, r) => a + r.total, 0)
  const nonZeroRows = tableRows.filter((r) => r.total > 0)
  const highest = nonZeroRows.reduce((max, r) => (r.total > (max?.total || 0) ? r : max), null)
  const lowest = nonZeroRows.reduce((min, r) => (r.total < (min?.total || Infinity) ? r : min), null)
  const average = nonZeroRows.length ? totalSpending / nonZeroRows.length : 0

  drawSummaryBox(doc, {
    title: 'Spending Summary',
    startY: y,
    items: [
      { label: 'Total Spending', value: formatCurrency(totalSpending, { detailed: true }) },
      { label: 'Highest Spending Month', value: highest ? `${highest.monthFull} (${formatCurrency(highest.total, { detailed: true })})` : '—' },
      { label: 'Lowest Spending Month', value: lowest ? `${lowest.monthFull} (${formatCurrency(lowest.total, { detailed: true })})` : '—' },
      { label: 'Average Monthly Spending', value: formatCurrency(average, { detailed: true }) },
    ],
  })

  // ── Page numbers ──
  const totalPages = doc.internal.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    addFooter(doc, i, totalPages)
  }

  doc.save(`monthly-spending-trend-${filters.year}.pdf`)
}

// PUBLIC: Export category allocation / spending-distribution PDF.
export async function exportBudgetAllocationPdf({ chartRef, categories, filters }) {
  const doc = initPdfDoc('portrait')
  const generatedAt = new Date().toLocaleString()
  const rows = (categories || []).filter((row) => Number(row.value) > 0)
  const total = rows.reduce((sum, row) => sum + Number(row.value || 0), 0)
  const totalRecords = rows.reduce((sum, row) => sum + Number(row.count || 0), 0)

  let y = drawReportHeader(doc, {
    title: 'Actual Expenses by Category',
    year: filters.year,
    month: filters.month,
    view: filters.view,
    generatedAt,
  })

  const chartImg = await captureChartImage(chartRef)
  if (chartImg) {
    y = checkPageBreak(doc, y, 91)
    doc.setFontSize(10)
    doc.setFont('Roboto', 'bold')
    setColor(doc, COLORS.dark)
    doc.text('Recorded Expense Distribution', MARGIN, y)
    y += 5

    doc.setDrawColor(...COLORS.line)
    doc.setLineWidth(0.3)
    doc.roundedRect(MARGIN, y, CONTENT_W, 78, 2, 2, 'S')
    doc.addImage(chartImg.dataUrl, 'PNG', MARGIN + 2, y + 2, CONTENT_W - 4, 74)
    y += 84
  }

  y = checkPageBreak(doc, y, 20)
  doc.setFontSize(11)
  doc.setFont('Roboto', 'bold')
  setColor(doc, COLORS.dark)
  doc.text('Expense Table', MARGIN, y)
  y += 6

  y = drawDataTable(doc, {
    startY: y,
    columns: [
      { key: 'name', header: 'Category', width: 57 },
      { key: 'count', header: 'Records', align: 'right', width: 25 },
      { key: 'value', header: 'Actual Expenses', align: 'right', width: 54, format: (row) => formatCurrency(row.value, { detailed: true }) },
      { key: 'percent', header: 'Share', align: 'right', width: 38, format: (row) => formatPercentage(row.percent, 2) },
    ],
    rows,
  })

  const largest = rows[0] || null
  drawSummaryBox(doc, {
    title: 'Financial Summary',
    startY: y,
    items: [
      { label: 'Total Actual Expenses', value: formatCurrency(total, { detailed: true }) },
      { label: 'Expense Records', value: String(totalRecords) },
      { label: 'Categories Represented', value: String(rows.length) },
      { label: 'Largest Category', value: largest ? largest.name : '—' },
      { label: 'Largest Category Share', value: largest ? formatPercentage(largest.percent, 2) : '0.00%' },
    ],
  })

  const totalPages = doc.internal.getNumberOfPages()
  for (let page = 1; page <= totalPages; page += 1) {
    doc.setPage(page)
    addFooter(doc, page, totalPages)
  }

  const periodSlug = filters.view === 'monthly' ? `${filters.year}-${String(filters.month).padStart(2, '0')}` : filters.year
  doc.save(`budget-allocation-${periodSlug}.pdf`)
}

// ═══════════════════════════════════════════════════════════════════════════════
// PUBLIC: Export AI Analysis PDF (Approved Budget Distribution)
// ═══════════════════════════════════════════════════════════════════════════════

export async function exportAiAnalysisPdf({ chartRef, distribution, total, totalProjectsEvents, aiSummary, filters }) {
  const doc = initPdfDoc('portrait')
  const now = new Date()
  const generatedAt = now.toLocaleString()

  let y = drawReportHeader(doc, {
    title: 'Category Budget Distribution',
    year: filters.year,
    month: filters.month,
    view: filters.view,
    generatedAt,
  })

  const chartImg = await captureChartImage(chartRef)
  if (chartImg) {
    doc.setFontSize(10)
    doc.setFont('Roboto', 'bold')
    setColor(doc, COLORS.dark)

    // The pie + legend capture's height varies with the number of categories,
    // so fit it proportionally instead of stretching it into a fixed box —
    // stretching/clipping was cutting off legend text for longer lists.
    const maxBoxW = CONTENT_W - 4
    const maxBoxH = 100
    const { w: imgW, h: imgH } = fitImageBox(chartImg, maxBoxW, maxBoxH)
    const boxH = imgH + 6

    y = checkPageBreak(doc, y, boxH + 15)
    doc.text('Category Breakdown', MARGIN, y)
    y += 5

    doc.setDrawColor(...COLORS.line)
    doc.setLineWidth(0.3)
    doc.roundedRect(MARGIN, y, CONTENT_W, boxH, 2, 2, 'S')
    doc.addImage(chartImg.dataUrl, 'PNG', MARGIN + (CONTENT_W - imgW) / 2, y + 3, imgW, imgH)
    y += boxH + 6
  }

  y = checkPageBreak(doc, y, 20)
  doc.setFontSize(11)
  doc.setFont('Roboto', 'bold')
  setColor(doc, COLORS.dark)
  doc.text('Budget Summary Table', MARGIN, y)
  y += 6

  const totalCount = totalProjectsEvents ?? distribution.reduce((sum, row) => sum + (Number(row.count) || 0), 0)

  y = drawDataTable(doc, {
    startY: y,
    columns: [
      { key: 'name', header: 'Category', width: 50 },
      { key: 'value', header: 'Total Budget', align: 'right', width: 46, format: (row) => formatCurrency(row.value, { detailed: true }) },
      { key: 'percent', header: 'Percentage', align: 'right', width: 32, format: (row) => formatPercentage((row.value / total) * 100, 1) },
      { key: 'count', header: 'Projects/Events', align: 'right', width: 32, format: (row) => String(row.count ?? 0) },
    ],
    rows: distribution,
  })

  const largest = distribution[0] || null
  y = drawSummaryBox(doc, {
    title: 'Overall Summary',
    startY: y,
    items: [
      { label: 'Total Budget', value: formatCurrency(total, { detailed: true }) },
      { label: 'Number of Categories', value: String(distribution.length) },
      { label: 'Number of Projects/Events', value: String(totalCount) },
      { label: 'Largest Category', value: largest ? `${largest.name} (${formatPercentage((largest.value / total) * 100, 1)})` : '—' },
    ],
  })

  if (aiSummary) {
    y = checkPageBreak(doc, y, 30)
    doc.setFontSize(11)
    doc.setFont('Roboto', 'bold')
    setColor(doc, COLORS.brand)
    doc.text('AI Interpretation', MARGIN, y)
    y += 6

    doc.setFontSize(9)
    doc.setFont('Roboto', 'normal')
    setColor(doc, COLORS.text)
    const lines = doc.splitTextToSize(aiSummary, CONTENT_W)
    doc.text(lines, MARGIN, y)
  }

  const totalPages = doc.internal.getNumberOfPages()
  for (let page = 1; page <= totalPages; page += 1) {
    doc.setPage(page)
    addFooter(doc, page, totalPages)
  }

  const periodSlug = filters.view === 'monthly' ? `${filters.year}-${String(filters.month).padStart(2, '0')}` : filters.year
  doc.save(`category-budget-distribution-${periodSlug}.pdf`)
}

// ═══════════════════════════════════════════════════════════════════════════════
// PUBLIC: Export the Expenses page's period-scoped Expense Report
// ═══════════════════════════════════════════════════════════════════════════════

const REPORT_TYPE_LABELS = {
  monthly: 'Monthly',
  quarterly: 'Quarterly',
  yearly: 'Yearly',
}

// A restrained navy/gray/black/white palette for this report's own accents
// (rules, month bands, section headings) — kept separate from COLORS.brand,
// which other exports still use for their own header bars.
const EXPENSES_ACCENT = COLORS.dark

// Value text is clamped to the space its cell actually has, so a long
// category or status never runs under the figure sitting beside it.
function clampToWidth(doc, text, maxWidth) {
  const value = String(text ?? '—')
  if (doc.getTextWidth(value) <= maxWidth) return value
  let clipped = value
  while (clipped.length > 1 && doc.getTextWidth(`${clipped}…`) > maxWidth) {
    clipped = clipped.slice(0, -1)
  }
  return `${clipped.trim()}…`
}

// A compact two-column strip of label/value pairs, used wherever the report
// needs to state a handful of fields. It replaces the seven-row
// "Information | Value" tables that each ran a third of a page tall behind a
// header row that said nothing. `right` values are right-aligned to the page
// edge by default, which lines the money up into one clean column;
// `alignRightValues: false` keeps both halves reading as plain label/value
// pairs, which is what dates and counts want.
function drawInfoGrid(doc, { startY, left, right = [], alignRightValues = true }) {
  const rowCount = Math.max(left.length, right.length)
  if (!rowCount) return startY

  const halfW = CONTENT_W / 2
  const labelW = 34
  const padX = 3.5
  const rowH = 6.2
  const boxH = rowCount * rowH + 3

  const y = checkPageBreak(doc, startY, boxH + 6)

  doc.setFillColor(...COLORS.bgLight)
  doc.rect(MARGIN, y, CONTENT_W, boxH, 'F')
  doc.setDrawColor(...COLORS.line)
  doc.setLineWidth(0.15)
  doc.rect(MARGIN, y, CONTENT_W, boxH, 'S')

  let rowY = y + 1.5
  for (let i = 0; i < rowCount; i += 1) {
    const baseline = rowY + rowH / 2 + 1.2
    const pairs = [left[i], right[i]]

    pairs.forEach((pair, side) => {
      if (!pair) return
      const colX = MARGIN + side * halfW

      doc.setFontSize(7.4)
      doc.setFont('Roboto', 'normal')
      setColor(doc, COLORS.muted)
      doc.text(pair.label, colX + padX, baseline)

      doc.setFontSize(8)
      doc.setFont('Roboto', 'bold')
      setColor(doc, pair.color || COLORS.dark)

      const available = halfW - labelW - padX * 2
      const text = clampToWidth(doc, pair.value, available)
      if (side === 1 && alignRightValues) {
        doc.text(text, MARGIN + CONTENT_W - padX, baseline, { align: 'right' })
      } else {
        doc.text(text, colX + padX + labelW, baseline)
      }
    })

    rowY += rowH
  }

  return y + boxH + SPACE.md
}

// Top-level heading for one of the report's own sections. Title case and
// bold, one clear step above the small letter-spaced uppercase captions the
// tables use for their columns, so the two never compete.
//
// `followedBy` is the room whatever it introduces will itself insist on — a
// heading has no business fitting on a page its own section can't start on.
function drawSectionLabel(doc, { text, startY, followedBy = 0 }) {
  const y = checkPageBreak(doc, startY, SPACE.sm + 1 + Math.max(11, followedBy))
  doc.setFontSize(9.5)
  doc.setFont('Roboto', 'bold')
  setColor(doc, COLORS.dark)
  doc.text(text, MARGIN, y)
  return y + SPACE.sm + 1
}

// A month's own banded heading, used to split Quarterly and Yearly reports
// into per-month sections. Not drawn for Monthly reports — a report already
// scoped to one month doesn't need a second heading announcing it.
//
// `followedBy` is however much room whatever comes next is itself going to
// insist on. Reserving the band alone was not enough: the band would fit at
// the foot of a page, and then the record under it would demand a fresh one,
// leaving the month name stranded above a blank half-page.
function drawMonthHeading(doc, { label, startY, recordCount, followedBy = 0 }) {
  const bandH = 8
  const y = checkPageBreak(doc, startY, bandH + SPACE.md + followedBy)

  doc.setFillColor(...COLORS.bgLight)
  doc.rect(MARGIN, y, CONTENT_W, bandH, 'F')
  doc.setDrawColor(...EXPENSES_ACCENT)
  doc.setLineWidth(0.35)
  doc.line(MARGIN, y, MARGIN + CONTENT_W, y)
  doc.line(MARGIN, y + bandH, MARGIN + CONTENT_W, y + bandH)

  const baseline = y + bandH / 2 + 1.5
  doc.setFontSize(9)
  doc.setFont('Roboto', 'bold')
  setColor(doc, COLORS.dark)
  doc.text(String(label).toUpperCase(), MARGIN + 3.5, baseline, { charSpace: 0.35 })

  doc.setFontSize(7.4)
  doc.setFont('Roboto', 'normal')
  setColor(doc, COLORS.muted)
  const countLabel = recordCount === 1 ? '1 record' : `${recordCount} records`
  doc.text(countLabel, MARGIN + CONTENT_W - 3.5, baseline, { align: 'right' })

  return y + bandH + SPACE.md
}

// Anywhere the report has to say that something is empty — a month with no
// records, a record with no transactions — it says so inside the same light
// bordered box, at the width of the table that would otherwise be there, so
// the absence reads as stated rather than as a gap where a table failed to
// render. Yearly reports run a lot of these.
const EMPTY_NOTE_H = 9

function drawEmptyNote(doc, { startY, text }) {
  const boxH = EMPTY_NOTE_H
  const y = checkPageBreak(doc, startY, boxH + 6)

  doc.setDrawColor(...COLORS.line)
  doc.setLineWidth(0.15)
  doc.rect(MARGIN, y, CONTENT_W, boxH, 'S')
  doc.setFontSize(7.8)
  doc.setFont('Roboto', 'normal')
  setColor(doc, COLORS.muted)
  doc.text(text, PAGE_W / 2, y + boxH / 2 + 1.2, { align: 'center' })

  return y + boxH + SPACE.md
}

// A rough (slight under-)estimate of a record's section height, assuming
// none of its cells wrap to more than one line — enough to decide whether
// starting it fresh on the next page keeps it in one piece. Undercounting
// only means a record with a lot of wrapped text still splits naturally
// (handled correctly either way), never an infinite loop forcing new pages.
function estimateRecordSectionHeight(record) {
  const titleH = 6.5
  const summaryH = 4 * 6.2 + 3 + SPACE.md // the four-row summary strip
  const breakdownH = record.transactions.length
    ? 7.4 + record.transactions.length * 6.8 + 7.8 + SPACE.md // header + rows + total
    : 9 + SPACE.md
  return titleH + summaryH + breakdownH + SPACE.sm
}

// The smallest block of a record that has to stay together when the record
// does have to split across a page: its title, its summary strip, and the
// first line or two of its expense table. Splitting any tighter than this
// leaves an orphaned record name at the foot of a page.
const RECORD_MIN_BLOCK = 46

// Short records are worth pulling onto a fresh page whole; long ones are let
// flow, because forcing those to start fresh is what was leaving half-empty
// pages behind. This is the one place that decision is made, so the month
// heading above a record can reserve exactly what the record will demand.
function recordSpaceDemand(record) {
  const estimatedHeight = estimateRecordSectionHeight(record)
  const freshPageCapacity = PAGE_H - (MARGIN + 8) - BOTTOM_RESERVE
  return estimatedHeight <= freshPageCapacity * 0.55 ? estimatedHeight : RECORD_MIN_BLOCK
}

// One approved Project/Event/Payroll record: a title line, a compact
// two-column summary strip, then its expense transactions as a single ruled
// table closed by its own total row.
function drawRecordSection(doc, { record, startY }) {
  let y = checkPageBreak(doc, startY, recordSpaceDemand(record))

  // A title is drawn from its baseline while the strips and tables below it
  // are drawn from their top edge, so without this nudge the name sits a
  // couple of millimetres tighter under whatever precedes it than every
  // other block does, and reads as part of that heading.
  y += SPACE.xs

  // Title line: the record's name on the left, its type on the right, so the
  // eye finds names down one edge instead of reading past a parenthetical to
  // get to the next one.
  doc.setFontSize(7.4)
  doc.setFont('Roboto', 'normal')
  setColor(doc, COLORS.muted)
  const typeText = String(record.type).toUpperCase()
  const typeWidth = doc.getTextWidth(typeText) + 6
  doc.text(typeText, MARGIN + CONTENT_W, y, { align: 'right', charSpace: 0.3 })

  doc.setFontSize(10)
  doc.setFont('Roboto', 'bold')
  setColor(doc, COLORS.dark)
  doc.text(clampToWidth(doc, record.name, CONTENT_W - typeWidth), MARGIN, y)
  y += SPACE.sm

  y = drawInfoGrid(doc, {
    startY: y,
    left: [
      { label: 'Category', value: record.category },
      { label: 'Status', value: record.status },
      { label: 'Utilization', value: `${formatPercentage(record.utilization, 1)} — ${record.utilizationStatus}` },
    ],
    right: [
      { label: 'Approved Budget', value: formatCurrency(record.approvedBudget, { detailed: true }) },
      { label: 'Actual Expenses', value: formatCurrency(record.totalExpenses, { detailed: true }) },
      {
        label: 'Remaining Balance',
        value: formatCurrency(record.remainingBudget, { detailed: true }),
        color: record.remainingBudget < 0 ? COLORS.danger : COLORS.dark,
      },
      {
        label: 'Returned Budget',
        value: record.returnedBudget > 0 ? formatCurrency(record.returnedBudget, { detailed: true }) : 'None',
      },
    ],
  })

  if (record.transactions.length) {
    y = drawDataTable(doc, {
      startY: y,
      ruled: true,
      columns: [
        { key: 'dateLabel', header: 'Date', width: 26 },
        { key: 'description', header: 'Particulars', width: CONTENT_W - 26 - 40 },
        { key: 'amount', header: 'Amount', align: 'right', width: 40, format: (r) => formatCurrency(r.amount, { detailed: true }) },
      ],
      rows: record.transactions,
      totalRow: {
        label: 'Total Expenses',
        value: formatCurrency(record.totalExpenses, { detailed: true }),
      },
    })
  } else {
    y = drawEmptyNote(doc, { startY: y, text: 'No expense transactions recorded for this record.' })
  }

  return y + SPACE.sm
}

// The height of the month band (when one is drawn) plus whatever the first
// thing under it will demand — what the Expense Breakdown heading has to
// have available before it is worth drawing at all.
const MONTH_BAND_H = 8

function monthBlockDemand(monthData, reportType) {
  const under = monthData.records.length
    ? recordSpaceDemand(monthData.records[0])
    : EMPTY_NOTE_H
  return reportType === 'monthly' ? under : MONTH_BAND_H + SPACE.md + under
}

// The report-level amounts table — used for both the opening Overall
// Financial Summary and the closing Report Totals so the two read as the
// same kind of statement rather than two differently-shaped ones.
function amountsTableHeight(rowCount) {
  return 7.4 + rowCount * 6.8 + 7.8 // header + rows + total row
}

function drawAmountsTable(doc, { startY, rows, totalRow }) {
  return drawDataTable(doc, {
    startY,
    ruled: true,
    columns: [
      { key: 'label', header: 'Particulars', width: CONTENT_W - 50 },
      { key: 'value', header: 'Amount', align: 'right', width: 50, colorFor: (row) => row.color || COLORS.dark },
    ],
    rows,
    totalRow,
  })
}

export async function exportExpensesReportPdf({ reportType, reportTitle, periodLabel, periodSlug, months, overall, preparedBy }) {
  const doc = initPdfDoc('portrait')
  const now = new Date()
  const generatedDate = now.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })
  const generatedTime = now.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' })
  const typeLabel = REPORT_TYPE_LABELS[reportType] || 'Expense'
  const remainingColor = overall.remainingBudget < 0 ? COLORS.danger : COLORS.dark

  let y = await drawOfficialLetterheadHeader(doc, {
    title: reportTitle || `${typeLabel} Expense Report`,
    subtitle: reportType === 'monthly' ? `For the Month of ${periodLabel}` : undefined,
  })

  y = drawSectionLabel(doc, { text: 'Report Information', startY: y })
  y = drawInfoGrid(doc, {
    startY: y,
    alignRightValues: false,
    left: [
      { label: 'Report Type', value: `${typeLabel} Report` },
      { label: 'Period Covered', value: periodLabel },
    ],
    right: [
      { label: 'Date Generated', value: generatedDate },
      { label: 'Time Generated', value: generatedTime },
    ],
  })

  // The money and the record counts answer two different questions, so they
  // get two different blocks: a ruled amounts table that closes on the
  // remaining balance, then a plain strip of how many records produced it.
  // Listing a record count under a column headed "Amount" is most of what
  // made the old summary hard to read.
  y = drawSectionLabel(doc, { text: 'Overall Financial Summary', startY: y, followedBy: amountsTableHeight(3) })
  y = drawAmountsTable(doc, {
    startY: y,
    rows: [
      { label: 'Total Approved Budget', value: formatCurrency(overall.totalBudget, { detailed: true }) },
      { label: 'Actual Expenses', value: formatCurrency(overall.totalExpenses, { detailed: true }) },
      { label: 'Returned Budget', value: formatCurrency(overall.totalReturnedBudget, { detailed: true }) },
    ],
    totalRow: {
      label: 'Remaining Budget',
      value: formatCurrency(overall.remainingBudget, { detailed: true }),
      color: remainingColor,
    },
  })
  y = drawInfoGrid(doc, {
    startY: y,
    alignRightValues: false,
    left: [
      { label: 'Approved Allocations', value: String(overall.approvedAllocations) },
      { label: 'Projects', value: String(overall.projectCount) },
    ],
    right: [
      { label: 'Events', value: String(overall.eventCount) },
      { label: 'Payroll Records', value: String(overall.payrollCount) },
    ],
  })

  y += SPACE.xs
  y = drawSectionLabel(doc, {
    text: reportType === 'monthly' ? 'Expense Breakdown' : 'Expense Breakdown by Month',
    startY: y,
    followedBy: months.length ? monthBlockDemand(months[0], reportType) : 0,
  })

  months.forEach((monthData) => {
    if (reportType !== 'monthly') {
      y = drawMonthHeading(doc, {
        label: monthData.label,
        startY: y,
        recordCount: monthData.records.length,
        followedBy: monthData.records.length
          ? recordSpaceDemand(monthData.records[0])
          : EMPTY_NOTE_H,
      })
    }

    // Both branches close on the same trailing gap, so every month sits the
    // same distance from the next one whether it held records or not — an
    // empty month that hugged the following band was the giveaway that the
    // spacing was being decided per-branch rather than by one rhythm.
    if (!monthData.records.length) {
      y = drawEmptyNote(doc, {
        startY: y,
        text: 'No approved Projects, Events, or Payroll records for this month.',
      })
      y += SPACE.sm
    } else {
      monthData.records.forEach((record) => {
        y = drawRecordSection(doc, { record, startY: y })
      })
    }

    y += SPACE.xs
  })

  y = drawSectionLabel(doc, { text: 'Report Totals', startY: y, followedBy: amountsTableHeight(2) })
  y = drawAmountsTable(doc, {
    startY: y,
    rows: [
      {
        label: `Total Actual Expenses (${overall.approvedAllocations} record${overall.approvedAllocations === 1 ? '' : 's'})`,
        value: formatCurrency(overall.totalExpenses, { detailed: true }),
      },
      { label: 'Total Returned Budget', value: formatCurrency(overall.totalReturnedBudget, { detailed: true }) },
    ],
    totalRow: {
      label: 'Remaining Budget',
      value: formatCurrency(overall.remainingBudget, { detailed: true }),
      color: remainingColor,
    },
  })

  if (preparedBy) {
    y = checkPageBreak(doc, y, 16)
    doc.setFontSize(7.4)
    doc.setFont('Roboto', 'normal')
    setColor(doc, COLORS.muted)
    doc.text('Exported by', MARGIN, y)
    doc.setFontSize(8)
    doc.setFont('Roboto', 'bold')
    setColor(doc, COLORS.dark)
    doc.text(preparedBy, MARGIN, y + 4.4)
  }

  const totalPages = doc.internal.getNumberOfPages()
  for (let page = 1; page <= totalPages; page += 1) {
    doc.setPage(page)
    addFooter(doc, page, totalPages, {
      confidentialityNote: 'Confidential — for official SK use, auditing, and documentation purposes only.',
    })
  }

  doc.save(`expense-report-${reportType}-${periodSlug}.pdf`)
}
