// exportPdf.js — Professional PDF report generator for AI Analysis charts.
// Uses jsPDF for layout and html2canvas to capture Recharts SVG charts.
import { jsPDF } from 'jspdf'
import html2canvas from 'html2canvas'
import { formatCurrency, formatPercentage, MONTHS_FULL } from './analytics'
import { robotoRegularBase64, robotoBoldBase64 } from './robotoFont'

// ── Constants ──────────────────────────────────────────────────────────────────
const PAGE_W = 210    // A4 width mm
const PAGE_H = 297    // A4 height mm
const MARGIN = 18
const CONTENT_W = PAGE_W - MARGIN * 2
const FOOTER_Y = PAGE_H - 12

const COLORS = {
  brand:    [14, 107, 77],   // #0E6B4D
  dark:     [15, 31, 54],    // #0F1F36
  text:     [55, 65, 81],    // #374151
  muted:    [107, 114, 128], // #6B7280
  line:     [229, 231, 235], // #E5E7EB
  white:    [255, 255, 255],
  bgLight:  [249, 250, 251], // #F9FAFB
  danger:   [220, 107, 79],  // #DC6B4F
}

// ── Helpers ────────────────────────────────────────────────────────────────────

function initPdfDoc(orientation = 'portrait') {
  const doc = new jsPDF(orientation, 'mm', 'a4')
  doc.addFileToVFS('Roboto-Regular.ttf', robotoRegularBase64)
  doc.addFont('Roboto-Regular.ttf', 'Roboto', 'normal')
  doc.addFileToVFS('Roboto-Bold.ttf', robotoBoldBase64)
  doc.addFont('Roboto-Bold.ttf', 'Roboto', 'bold')
  doc.setFont('Roboto', 'normal')
  return doc
}

function setColor(doc, color) {
  doc.setTextColor(...color)
}

function drawLine(doc, y) {
  doc.setDrawColor(...COLORS.line)
  doc.setLineWidth(0.3)
  doc.line(MARGIN, y, PAGE_W - MARGIN, y)
}

function addFooter(doc, pageNum, totalPages) {
  doc.setFontSize(8)
  setColor(doc, COLORS.muted)
  doc.text(`Page ${pageNum} of ${totalPages}`, PAGE_W - MARGIN, FOOTER_Y, { align: 'right' })
  doc.text('Generated by Cuenta — SK Budget Monitoring System', MARGIN, FOOTER_Y)
}

function checkPageBreak(doc, y, needed = 30) {
  if (y + needed > PAGE_H - 20) {
    doc.addPage()
    return MARGIN + 10
  }
  return y
}

// ── Chart capture ──────────────────────────────────────────────────────────────

async function captureChartImage(chartContainerEl) {
  if (!chartContainerEl) return null
  // Find the recharts wrapper inside
  const recharts = chartContainerEl.querySelector('.recharts-responsive-container') || chartContainerEl
  try {
    const canvas = await html2canvas(recharts, {
      backgroundColor: '#ffffff',
      scale: 2,
      useCORS: true,
      logging: false,
    })
    return canvas.toDataURL('image/png')
  } catch (err) {
    console.warn('Chart capture failed:', err)
    return null
  }
}

// ── Report Header ──────────────────────────────────────────────────────────────

function drawReportHeader(doc, { title, year, generatedAt }) {
  let y = MARGIN

  // Brand bar
  doc.setFillColor(...COLORS.brand)
  doc.rect(0, 0, PAGE_W, 4, 'F')

  // System name
  y += 8
  doc.setFontSize(10)
  setColor(doc, COLORS.brand)
  doc.setFont('Roboto', 'bold')
  doc.text('CUENTA', MARGIN, y)
  doc.setFont('Roboto', 'normal')
  setColor(doc, COLORS.muted)
  doc.setFontSize(8)
  doc.text('SK Budget Monitoring and Documentation Tracking with AI Analysis', MARGIN, y + 5)

  // Report title
  y += 16
  doc.setFontSize(18)
  doc.setFont('Roboto', 'bold')
  setColor(doc, COLORS.dark)
  doc.text(title, MARGIN, y)

  // Meta line
  y += 8
  doc.setFontSize(9)
  doc.setFont('Roboto', 'normal')
  setColor(doc, COLORS.muted)
  const metaLine = `Year: ${year}  •  Generated: ${generatedAt}`
  doc.text(metaLine, MARGIN, y)

  y += 4
  drawLine(doc, y)

  return y + 8
}

// ── Data Table ─────────────────────────────────────────────────────────────────

function drawDataTable(doc, { columns, rows, startY }) {
  let y = startY
  const colWidths = columns.map((c) => c.width || Math.floor(CONTENT_W / columns.length))

  // Adjust last column to fill remaining width
  const usedWidth = colWidths.slice(0, -1).reduce((a, b) => a + b, 0)
  colWidths[colWidths.length - 1] = CONTENT_W - usedWidth

  // Header row
  y = checkPageBreak(doc, y, 16)
  doc.setFillColor(...COLORS.brand)
  doc.rect(MARGIN, y - 4, CONTENT_W, 8, 'F')
  doc.setFontSize(8)
  doc.setFont('Roboto', 'bold')
  setColor(doc, COLORS.white)

  let x = MARGIN + 3
  columns.forEach((col, i) => {
    const align = col.align === 'right' ? x + colWidths[i] - 6 : x
    const textAlign = col.align === 'right' ? { align: 'right' } : {}
    doc.text(col.header, align, y, textAlign)
    x += colWidths[i]
  })
  y += 7

  // Data rows
  doc.setFont('Roboto', 'normal')
  doc.setFontSize(8)
  rows.forEach((row, rowIndex) => {
    y = checkPageBreak(doc, y, 10)
    // Alternating row bg
    if (rowIndex % 2 === 0) {
      doc.setFillColor(...COLORS.bgLight)
      doc.rect(MARGIN, y - 4, CONTENT_W, 7, 'F')
    }

    x = MARGIN + 3
    columns.forEach((col, i) => {
      const value = col.format ? col.format(row) : String(row[col.key] ?? '—')
      const isNegative = col.highlightNegative && typeof row[col.key] === 'number' && row[col.key] < 0
      setColor(doc, isNegative ? COLORS.danger : COLORS.text)
      const align = col.align === 'right' ? x + colWidths[i] - 6 : x
      const textAlign = col.align === 'right' ? { align: 'right' } : {}
      doc.text(value, align, y, textAlign)
      x += colWidths[i]
    })
    y += 7
  })

  return y + 4
}

// ── Summary Box ────────────────────────────────────────────────────────────────

function drawSummaryBox(doc, { title, items, startY }) {
  let y = checkPageBreak(doc, startY, 10 + items.length * 8)

  // Section header
  doc.setFontSize(11)
  doc.setFont('Roboto', 'bold')
  setColor(doc, COLORS.dark)
  doc.text(title, MARGIN, y)
  y += 4

  // Soft box
  const boxH = items.length * 9 + 12
  y = checkPageBreak(doc, y, boxH + 4)
  doc.setFillColor(...COLORS.bgLight)
  doc.setDrawColor(...COLORS.line)
  doc.roundedRect(MARGIN, y - 2, CONTENT_W, boxH, 3, 3, 'FD')

  y += 6
  items.forEach((item) => {
    doc.setFontSize(8.5)
    doc.setFont('Roboto', 'normal')
    setColor(doc, COLORS.muted)
    doc.text(item.label, MARGIN + 6, y)

    doc.setFont('Roboto', 'bold')
    setColor(doc, item.color || COLORS.dark)
    doc.text(item.value, MARGIN + CONTENT_W - 10, y, { align: 'right' })
    y += 9
  })

  return y + 6
}

// ── Graph Structure Box ────────────────────────────────────────────────────────

function drawGraphStructure(doc, { title, items, startY }) {
  let y = checkPageBreak(doc, startY, 10 + items.length * 7)

  doc.setFontSize(10)
  doc.setFont('Roboto', 'bold')
  setColor(doc, COLORS.dark)
  doc.text(title, MARGIN, y)
  y += 6

  items.forEach((item) => {
    y = checkPageBreak(doc, y, 7)
    doc.setFontSize(8)
    doc.setFont('Roboto', 'bold')
    setColor(doc, COLORS.brand)
    doc.text('•', MARGIN + 4, y)
    doc.text(item.label + ':', MARGIN + 9, y)
    doc.setFont('Roboto', 'normal')
    setColor(doc, COLORS.text)
    doc.text(item.value, MARGIN + 9 + doc.getTextWidth(item.label + ':  '), y)
    y += 7
  })

  return y + 4
}

// ═══════════════════════════════════════════════════════════════════════════════
// PUBLIC: Export Budget vs Actual PDF
// ═══════════════════════════════════════════════════════════════════════════════

export async function exportBudgetVsActualPdf({ chartRef, bva, filters }) {
  const doc = initPdfDoc('portrait')
  const now = new Date()
  const generatedAt = now.toLocaleString()

  // ── Page 1: Header ──
  let y = drawReportHeader(doc, {
    title: 'Chart for Budget',
    year: filters.year,
    generatedAt,
  })

  // ── Chart Image ──
  const chartImg = await captureChartImage(chartRef)
  if (chartImg) {
    y = checkPageBreak(doc, y, 85)
    doc.setFontSize(10)
    doc.setFont('Roboto', 'bold')
    setColor(doc, COLORS.dark)
    doc.text('Allocated Budget vs Approved Spending', MARGIN, y)
    y += 4

    // Subtle border around chart
    doc.setDrawColor(...COLORS.line)
    doc.setLineWidth(0.3)
    doc.roundedRect(MARGIN, y, CONTENT_W, 72, 2, 2, 'S')
    doc.addImage(chartImg, 'PNG', MARGIN + 2, y + 2, CONTENT_W - 4, 68)
    y += 78
  }

  // ── Graph Structure ──
  y = drawGraphStructure(doc, {
    title: 'Graph Structure',
    startY: y,
    items: [
      { label: 'X-Axis', value: 'Months' },
      { label: 'Y-Axis', value: 'Amount (₱)' },
      { label: 'Series 1', value: 'Allocated Budget' },
      { label: 'Series 2', value: 'Approved Spending' },
    ],
  })

  // ── Data Table ──
  y = checkPageBreak(doc, y, 20)
  doc.setFontSize(11)
  doc.setFont('Roboto', 'bold')
  setColor(doc, COLORS.dark)
  doc.text('Budget vs Spending Data', MARGIN, y)
  y += 6

  const tableColumns = [
    { key: 'label', header: 'Month', width: 36 },
    { key: 'budget', header: 'Allocated Budget', align: 'right', width: 38, format: (r) => formatCurrency(r.budget, { detailed: true }) },
    { key: 'spending', header: 'Actual Expenses', align: 'right', width: 38, format: (r) => formatCurrency(r.spending, { detailed: true }) },
    { key: 'variance', header: 'Remaining Budget', align: 'right', width: 36, format: (r) => formatCurrency(r.variance, { detailed: true }), highlightNegative: true },
    { key: 'percentUsed', header: 'Utilization', align: 'right', width: 26, format: (r) => formatPercentage(r.percentUsed, 2) },
  ]

  y = drawDataTable(doc, {
    columns: tableColumns,
    rows: bva.rowsWithData,
    startY: y,
  })

  // ── Budget Summary ──
  const totalBudget = bva.totalBudget
  const totalSpending = bva.totalSpending
  const totalVariance = bva.totalVariance
  const overallUtilization = totalBudget > 0 ? (totalSpending / totalBudget) * 100 : 0

  y = drawSummaryBox(doc, {
    title: 'Budget Summary',
    startY: y,
    items: [
      { label: 'Total Allocated Budget', value: formatCurrency(totalBudget, { detailed: true }) },
      { label: 'Total Actual Expenses', value: formatCurrency(totalSpending, { detailed: true }) },
      { label: 'Total Remaining Budget', value: formatCurrency(totalVariance, { detailed: true }), color: totalVariance < 0 ? COLORS.danger : COLORS.brand },
      { label: 'Overall Utilization', value: formatPercentage(overallUtilization, 2) },
    ],
  })

  // ── Page numbers ──
  const totalPages = doc.internal.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    addFooter(doc, i, totalPages)
  }

  doc.save(`budget-vs-actual-${filters.year}.pdf`)
}

// ═══════════════════════════════════════════════════════════════════════════════
// PUBLIC: Export Monthly Spending Trend PDF
// ═══════════════════════════════════════════════════════════════════════════════

export async function exportMonthlySpendingPdf({ chartRef, trend, tableRows, filters }) {
  const doc = initPdfDoc('portrait')
  const now = new Date()
  const generatedAt = now.toLocaleString()

  // ── Page 1: Header ──
  let y = drawReportHeader(doc, {
    title: 'Monthly Spending Trend',
    year: filters.year,
    generatedAt,
  })

  // ── Chart Image ──
  const chartImg = await captureChartImage(chartRef)
  if (chartImg) {
    y = checkPageBreak(doc, y, 85)
    doc.setFontSize(10)
    doc.setFont('Roboto', 'bold')
    setColor(doc, COLORS.dark)
    doc.text(`Monthly Spending — ${filters.year}`, MARGIN, y)
    y += 4

    doc.setDrawColor(...COLORS.line)
    doc.setLineWidth(0.3)
    doc.roundedRect(MARGIN, y, CONTENT_W, 72, 2, 2, 'S')
    doc.addImage(chartImg, 'PNG', MARGIN + 2, y + 2, CONTENT_W - 4, 68)
    y += 78
  }

  // ── Graph Structure ──
  y = drawGraphStructure(doc, {
    title: 'Graph Structure',
    startY: y,
    items: [
      { label: 'X-Axis', value: 'Months' },
      { label: 'Y-Axis', value: 'Spending Amount (₱)' },
      { label: 'Series', value: 'Actual Monthly Spending' },
    ],
  })

  // ── Data Table ──
  y = checkPageBreak(doc, y, 20)
  doc.setFontSize(11)
  doc.setFont('Roboto', 'bold')
  setColor(doc, COLORS.dark)
  doc.text('Monthly Spending Data', MARGIN, y)
  y += 6

  // Build change from previous month
  const dataWithChange = tableRows.map((r, i) => {
    const prev = i > 0 ? tableRows[i - 1].total : null
    const change = prev != null ? r.total - prev : null
    let trendDir = '—'
    if (change !== null) {
      trendDir = change > 0 ? 'Increasing' : change < 0 ? 'Decreasing' : 'Stable'
    }
    return { ...r, changeAmount: change, trendDirection: trendDir }
  })

  const tableColumns = [
    { key: 'monthFull', header: 'Month', width: 30 },
    { key: 'total', header: 'Total Spending', align: 'right', width: 36, format: (r) => formatCurrency(r.total, { detailed: true }) },
    { key: 'changeAmount', header: 'Change', align: 'right', width: 36, format: (r) => r.changeAmount !== null ? (r.changeAmount > 0 ? '+' : '') + formatCurrency(r.changeAmount, { detailed: true }) : '—', highlightNegative: false },
    { key: 'trendDirection', header: 'Trend', width: 24 },
    { key: 'count', header: 'Approved', align: 'right', width: 20, format: (r) => String(r.count) },
    { key: 'missing', header: 'Missing Receipts', align: 'right', width: 28, format: (r) => String(r.missing) },
  ]

  y = drawDataTable(doc, {
    columns: tableColumns,
    rows: dataWithChange,
    startY: y,
  })

  // ── Spending Summary ──
  const totalSpending = tableRows.reduce((a, r) => a + r.total, 0)
  const nonZeroRows = tableRows.filter((r) => r.total > 0)
  const highest = nonZeroRows.reduce((max, r) => (r.total > (max?.total || 0) ? r : max), null)
  const lowest = nonZeroRows.reduce((min, r) => (r.total < (min?.total || Infinity) ? r : min), null)
  const average = nonZeroRows.length ? totalSpending / nonZeroRows.length : 0

  y = drawSummaryBox(doc, {
    title: 'Spending Summary',
    startY: y,
    items: [
      { label: 'Total Spending', value: formatCurrency(totalSpending, { detailed: true }) },
      { label: 'Highest Spending Month', value: highest ? `${highest.monthFull} (${formatCurrency(highest.total, { detailed: true })})` : '—' },
      { label: 'Lowest Spending Month', value: lowest ? `${lowest.monthFull} (${formatCurrency(lowest.total, { detailed: true })})` : '—' },
      { label: 'Average Monthly Spending', value: formatCurrency(average, { detailed: true }) },
    ],
  })

  // ── Page numbers ──
  const totalPages = doc.internal.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    addFooter(doc, i, totalPages)
  }

  doc.save(`monthly-spending-trend-${filters.year}.pdf`)
}
